### ISSUE TITLE
HMAC?

### ISSUE THREAD

**Issue by krestenkrab** [jlouis/curve_tun#2]
Maybe this is not as much an issue as it is a question.

When transmitting messages, these are encoded with `enacl:box`.  However, as I understand this only does encryption, no integrity (HASH / MAC) of the data contents.  As I understand it, a box is the result of XOR'ing the message contents with the output of some RNG seeded by the NONCE and the keys.  Also, the crypto_box API specifies that the output is the same size as the input.

So, if I want integrity; should I include a HMAC inside the message?  Or should we add it to the protocol?

**Comment by krestenkrab** [comment]
Hm, I didn't read the documentation correctly:

> The crypto_box function encrypts and _authenticates_ a message m using the sender's secret key sk, the receiver's public key pk, and a nonce n. 

But how can it both encrypt and authenticate when the cipher text has the same length as the clear text?

**Comment by jedisct1** [comment]
They don't have the same length.

The ciphertext includes `crypto_box_MACBYTES` extra bytes for the authenticator.

See http://doc.libsodium.org/public-key_cryptography/authenticated_encryption.html

```
c should be at least crypto_box_MACBYTES + mlen bytes long.

This function writes the authentication tag, whose length is crypto_box_MACBYTES bytes, in c, 
immediately followed by the encrypted message, whose length is the same as the plaintext: mlen.
```

**Comment by ahf** [comment]
It's not using the high-level lib sodium `_easy` functions.

See the note on 0-padding here: http://nacl.cr.yp.to/box.html

**Comment by jlouis** [comment]
Exactly, not using the `_easy` functions, but it _is_ padding correctly internally. here is an example:

```
    2> #{public := PK, secret := SK} = enacl:box_keypair().
    #{public => <<206,136,26,101,39,84,50,40,40,239,124,206,187,186,227,
        204,142,252,139,42,232,32,31,119,17,145,95,201,...>>,
      secret => <<23,254,6,64,248,250,135,56,187,61,110,60,125,148,157,
        188,138,53,18,113,33,58,46,248,213,7,246,...>>}
    3> byte_size(enacl:box(<<>>, <<0:192>>, PK, SK)).
    16
```

Encrypting the empty string with a 192 bit nonce of all zeroes with a little bit of keypair-abuse gives 16 bytes of output, which is exactly the 256 bits of HMAC.

Edit s/256 bytes/256 bits/g :)

**Comment by jlouis** [comment]
Which reminds me that `enacl` should perhaps use the _easy functions an avoid some allocations for more speed and simpler data flow.

**Comment by krestenkrab** [comment]
Hm, ... shouldn't https://github.com/jlouis/enacl/blob/master/c_src/enacl_nif.c#L194 then add `crypto_box_MACBYTES` to the allocated output buffer then?

**Comment by ahf** [comment]
It's not using the high-level API of libsodium. Check the NaCl documentation on this - it's adding padding in the Erlang code. See: https://github.com/jlouis/enacl/blob/master/src/enacl.erl#L200-L205

**Comment by jlouis** [comment]
I'm sorry, I didn't want to write C code, so I did most of this work in the Erlang layer instead. But you should be able to remove the Erlang lines and use the `_easy` variants if you want.

**Comment by krestenkrab** [comment]
Correct. It's not using the `_easy` API, and it _is_ doing the zero-padding correctly, but AFAICS it's not including a MAC.

**Comment by ahf** [comment]
It's using the zero-padded buffer for storing the MAC:

```
(talla@sobek)1> #{public := PK, secret := SK} = enacl:box_keypair().
#{public => <<128,105,81,128,239,157,83,49,139,207,235,102,19,71,117,
    95,157,147,55,26,17,181,222,127,54,118,107,220,...>>,
  secret => <<249,90,100,255,184,226,89,180,162,159,111,235,14,100,
    153,134,165,27,33,110,98,116,71,15,132,122,25,...>>}
(talla@sobek)2> enacl:box(<<>>, <<0:192>>, PK, SK).
<<66,124,247,199,206,104,177,124,11,90,231,117,12,139,108,
  133>>
```

**Comment by jlouis** [comment]
It is:

```
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [kernel-poll:false]

Eshell V6.3.1  (abort with ^G)
1> #{ public := PK, secret := SK} = enacl:box_keypair(),
1> ok.
ok
2> enacl:box(<<"hello world">>, <<0:192>>, PK, SK).
<<196,121,191,65,23,118,20,230,14,40,133,99,250,208,90,
  239,96,199,76,62,25,155,255,194,205,58,198>>
3> %% First 16 bytes in v(2) is the authenticator
3> enacl:box_open(v(2), <<0:192>>, PK, SK).
{ok,<<"hello world">>}
```

Also, we can't open the box if the authenticator is wrong. Here we manipulate the first byte of the authenticator:

```
4> <<_, Wrong/binary>> = v(2).
<<196,121,191,65,23,118,20,230,14,40,133,99,250,208,90,
  239,96,199,76,62,25,155,255,194,205,58,198>>
5> enacl:box_open(<<1, Wrong/binary>>, <<0:192>>, PK, SK).
{error,failed_verification}
```

Finally, we have QuickCheck verification one way around the isomorphism: https://github.com/jlouis/enacl/blob/master/eqc_test/enacl_eqc.erl#L142-190 which establishes we can't open messages where the authenticator has been manipulated. The only thing missing is a verification of the Lange/Schwabe/Bernstein examples, but I'm pretty sure they hold as well.

**Comment by krestenkrab** [comment]
Ah! It was the difference between `crypto_box_BOXZEROBYTES` and `crypto_box_ZEROBYTES` that caught me off.  The first is 16, the latter is 32.  Sorry for the confusion.

And BTW, no, I don't think you should be using the `_easy` version, because then you can't reuse a `k` (result of `_beforem`) between messages in the same session.  Which is an obvious optimisation to do at some point.

**Comment by jedisct1** [comment]
Even if it's using the `box` API, it might be a good idea for `enacl` to remove the padding. None of the bindings for other languages requires/returns data prepended with extra padding.

**Comment by krestenkrab** [comment]
Perhaps as a clarification, https://github.com/jlouis/enacl/blob/master/c_src/enacl_nif.c#L203 should read 

``` erlang
    return enif_make_sub_binary(
         env,
         enif_make_binary(env, &result),
         crypto_box_ZEROBYTES - crypto_box_BOXZEROBYTES,
         padded_msg.size - crypto_box_ZEROBYTES - crypto_box_BOXZEROBYTES);
```

in stead.  Just to make it clear what's going on :-)

**Comment by jedisct1** [comment]
@krestenkrab  The `_easy` API supports a precalculated shared key: http://doc.libsodium.org/public-key_cryptography/authenticated_encryption.html#precalculation-interface

**Comment by jlouis** [comment]
@jedisct1 `enacl` doesn't require the extra padding either in its API, but prepends the padding on the Erlang side automatically for every message that is boxed. That is, we can switch to `_easy` style functions with no API change. The lower level NIF C implementation requires the padding, but that is internal binding detail and where the `_easy` change can happen.

Or maybe we don't understand each other.

**Comment by jedisct1** [comment]
Excellent, then.

I was confused by the messages stating that the input and the output had the same length, hence didn't include a MAC. Thought this was referring the `enacl` API, not its internals.
